### ISSUE TITLE
NoHttpResponseException not bubbled up by ApacheHttpClientTransport, returns 400 instead

### ISSUE THREAD

**Issue by aboivin** [checkout/checkout-sdk-java#300]
Hi, 

It appears that the ApacheHttpClientTransport is not properly bubbling up NoHttpResponseException and instead returning a 400. This makes it difficult to properly handle and retry requests without having to retry on all 400 errors.

Is it possible to have the ApacheHttpClientTransport either bubble up the exception or return a 5xx http code when a NoHttpResponseException is encountered?

https://github.com/checkout/checkout-sdk-java/blob/6c95afe5ab0e2e93f79e7bd0d179bcb3ce2f6484/src/main/java/com/checkout/ApacheHttpClientTransport.java#L168

```
org.apache.http.NoHttpResponseException: api.checkout.com:443 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.checkout.ApacheHttpClientTransport.performCall(ApacheHttpClientTransport.java:154)
	at com.checkout.ApacheHttpClientTransport.lambda$invoke$1(ApacheHttpClientTransport.java:110)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Thanks for you help

**Comment by Armando-Ibarra** [comment]
Hey @aboivin 
Thanks for opening this.

I'm wondering if that was only a blip, I'm not pretty sure if that is really a `500` because it is not really a Server Side error, how many times have you found this issue?

We can wrap that exception to a custom error, but just wanted to confirm on which cases this error appears.

**Comment by aboivin** [comment]
Hey, thanks for responding
I confirm it's not a `500`
`NoHttpResponseException` means that the origin server or any of intermediate proxy hops dropped connection without returning a valid response.
We encounter this issue ~20/week mostly when requesting a payment or capturing a payment
A custom error would be great, let me know if you need any additional info

**Comment by Armando-Ibarra** [comment]
Okay @aboivin It's hard to tell the root cause, because I know that some months ago we had some issues with the balancer, this probably is not the case, but at least I'll add a wrapper exception. Let you know when it's ready next week

**Comment by Armando-Ibarra** [comment]
Sorry for the delay on this, release #313 let us know if you face any problem
